// Generated by CoffeeScript 1.9.3
(function() {
  this.natural = {
    style: 'natural.mss',
    variaticValues: [],
    queries: {
      zoom: {
        '8': {
          table: 'planet_osm_polygon',
          column: 'natural',
          values: ['wood', 'forest', 'water']
        }
      }
    }
  };

  this.water = {
    style: 'water.mss',
    variaticValues: [],
    queries: {
      zoom: {
        '8': {
          table: 'planet_osm_polygon',
          column: 'water',
          values: ['river', 'lake', 'reservoir', 'fish_pond', 'pond']
        }
      }
    }
  };

  this.waterway = {
    style: 'waterway.mss',
    variaticValues: [],
    queries: {
      zoom: {
        '8': {
          table: 'planet_osm_polygon',
          column: 'waterway',
          values: ['lock', 'pond', 'weir', 'reservoir', 'dam', 'river', 'riverbank', 'stream', 'lake']
        }
      }
    }
  };

  this.rail = {
    style: 'rail.mss',
    variaticValues: ['_link'],
    queries: {
      zoom: {
        '1': {
          table: 'planet_osm_roads',
          column: 'railway',
          values: ['rail']
        },
        '13': {
          table: 'planet_osm_line',
          column: 'railway',
          values: ['rail']
        }
      }
    }
  };

  this.roads = {
    style: 'roads.mss',
    variaticValues: ['_link'],
    queries: {
      zoom: {
        '1': {
          table: 'planet_osm_roads',
          column: 'highway',
          values: ['motorway', 'trunk']
        },
        '7': {
          table: 'planet_osm_roads',
          column: 'highway',
          values: ['motorway', 'trunk', 'primary', 'secondary']
        },
        '11': {
          table: 'planet_osm_line',
          column: 'highway',
          values: ['motorway', 'trunk', 'primary', 'secondary']
        },
        '12': {
          additionalValues: ['tertiary']
        },
        '13': {
          additionalValues: ['residential']
        },
        '14': {
          additionalValues: ['living_street']
        },
        '15': {
          additionalValues: ['service', 'footway', 'track']
        }
      }
    }
  };

  this.roadtext = {
    style: 'roadtext.mss',
    variaticValues: [],
    noTolerance: true,
    queries: {
      zoom: {
        '13': {
          table: 'planet_osm_line',
          column: 'highway',
          values: ['residential']
        },
        '14': {
          additionalValues: ['living_street']
        },
        '15': {
          additionalValues: ['service', 'footway', 'track']
        }
      }
    }
  };

}).call(this);
